import React from "react";
import { useForm } from "react-hook-form";
import { useMemo, useEffect, useState } from "react";
import PageTitle from "@/components/PageTitle";
import Table from "@/components/Table";
import { PaginationType } from "@/types/commonTypes";
import usePagination from "@/hooks/usePagination";
import PageHeader from "@/components/PageHeader";
import { useNavigate } from "react-router-dom";
import { BANK_ADD_ROUTE } from "@/routes/routeNames";
import { MdEditSquare } from "react-icons/md";
import DeleteModal from "@/components/DeleteModal";
import PageFilterWrapper from "@/components/PageFilterWrapper";
import PageFilterSample from "@/components/PageFilterSample";
import { FilterInput } from "@/components/Input/filterInput";
import { buildQueryString } from "@/utils/generalHelper";
import { useGetApiQuery } from "@/redux/services/crudApi";
import Spinner from "@/components/Spinner";

const Banks: React.FC = () => {
  const navigate = useNavigate();
  const [open, setOpen] = React.useState<boolean>(false);
  const [deleteId, setDeleteId] = React.useState<number | null>(null);
  const { query, handlePagination } = usePagination({ page: 1, limit: 10 });
  const [queryString, setQueryString] = useState<Record<string, any>>({});

  const handleNewBank = (id: number | null) => {
    id === null ? navigate(BANK_ADD_ROUTE) : navigate(`${BANK_ADD_ROUTE}${id}`);
  };

  const handleDeleteTrigger = (id: number) => {
    setDeleteId(id);
    setOpen(true);
  };

  const handleDelete = async () => {
    // TODO: integrate delete API when ready
    // Example usage of deleteId to avoid unused warning
    // console.log("Deleting bank id:", deleteId);
    setOpen(false);
  };

  // Filter fields similar to Customer list
  const { control, handleSubmit } = useForm<{ bankName?: string; accountNumber?: string }>();

  const filterField = useMemo(
    () => [
      {
        name: "bankName",
        label: "Bank Name",
        Component: FilterInput,
        control,
      },
      {
        name: "accountNumber",
        label: "Account Number",
        Component: FilterInput,
        control,
      },
    ],
    [control],
  );

  const { Component } = PageFilterSample(
    filterField,
    handleSubmit,
    (qs: Record<string, any>) => setQueryString(qs),
  );

  const url = buildQueryString("account/list", {
    page: query.page,
    limit: query.limit,
    search: queryString,
  });

  const { data: bankList, isLoading: isBanksLoading, isSuccess, refetch } = useGetApiQuery({ url });

  useEffect(() => {
    refetch();
  }, [queryString]);

  const headers = [
    "S.N",
    "Account Name",
    "Account Number",
    "Account Type",
    "Bank Name",
    "Opening Balance",
    "Status",
    "Generated By",
    "Actions",
  ];

  // Build table data from API, fallback to mocked row if API not ready
  const apiData = isSuccess && bankList?.data?.data ? bankList.data.data : null;
  const data = apiData
    ? apiData.map((row: any, idx: number) => [
        (bankList?.data?.page - 1) * (bankList?.data?.limit || 10) + idx + 1,
        row?.accountName || "-",
        row?.accountNumber || "-",
        row?.accountType || "-",
        row?.bankName || "-",
        row?.openingBalance ?? "-",
        row?.status || "-",
        row?.createdBy?.name || row?.createdBy || "-",
        <div className="flex items-center justify-center gap-3" key={`actions-${row?.id || idx}`}>
          <MdEditSquare
            size={18}
            className="text-[#0090DD] hover:text-blue-800"
            onClick={() => handleNewBank(row?.id || idx)}
          />

          <DeleteModal
            open={open}
            setOpen={setOpen}
            handleDeleteTrigger={() => handleDeleteTrigger(row?.id || idx)}
            handleConfirmDelete={handleDelete}
          />
        </div>,
      ])
    : [
        [
          "1",
          "Account Name",
          "Account Number",
          "Account Type",
          "Bank Name",
          "Opening Balance",
          "Status",
          "Generated By",
          <div className="flex items-center justify-center gap-3" key="actions-1">
            <MdEditSquare
              size={18}
              className="text-[#0090DD] hover:text-blue-800"
              onClick={() => handleNewBank(1)}
            />

            <DeleteModal
              open={open}
              setOpen={setOpen}
              handleDeleteTrigger={() => handleDeleteTrigger(1)}
              handleConfirmDelete={handleDelete}
            />
          </div>,
        ],
      ];

  const pagination: PaginationType = apiData
    ? {
        page: bankList?.data?.page ?? 1,
        limit: bankList?.data?.limit ?? query.limit,
        total: bankList?.data?.total ?? 0,
        totalPages: bankList?.data?.totalPages ?? 1,
      }
    : {
        page: query.page,
        limit: query.limit,
        total: data.length,
        totalPages: 1,
      };
  return (
    <>
      <PageTitle title="Accounts & Banks" />
      <PageHeader
        hasAddButton={true}
        newButtonText="Add Account"
        handleNewButton={() => handleNewBank(null)}
        handleReloadButton={() => {}}
      />
      <PageFilterWrapper title="Bank Filters">{Component}</PageFilterWrapper>
      {isBanksLoading ? (
        <Spinner className="flex justify-center items-center h-full" />
      ) : (
        <Table
        headers={headers}
        data={data}
        pagination={pagination}
        handlePagination={handlePagination}
        />
      )}
    </>
  );
};

export default Banks;
