import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import PageTitle from "@/components/PageTitle";
import Table from "@/components/Table";
import usePagination from "@/hooks/usePagination";
import { PaginationType } from "@/types/commonTypes";
import { CurrencySign } from "@/constants";
import RevenueFilter from "./RevenueFilter";
import { useDeleteApiMutation, useGetApiQuery } from "@/redux/services/crudApi";
import { buildQueryString } from "@/utils/generalHelper";
import { format } from "date-fns";
import BikramSambat, {ADToBS, BSToAD}  from "bikram-sambat-js"
import { REVENUE_ADD_ROUTE } from "@/routes/routeNames";
import { FiEdit2 } from "react-icons/fi";
import { MdEditSquare } from "react-icons/md";
import PageHeader from "@/components/PageHeader";
import DeleteModal from "@/components/DeleteModal";
import { handleError, handleResponse } from "@/utils/responseHandler";
import { REVENUE_URL } from "@/constants/apiUrlConstants";

const Revenue: React.FC = () => {
  const navigate = useNavigate();
  const { query, handlePagination } = usePagination({ page: 1, limit: 10 });

  const [open, setOpen] = useState<boolean>(false);
  const [deleteId, setDeleteId] = useState<number | null>(null);

  const [queryStringOptions, setQueryStringOptions] = useState({
    start: "",
    end: "",
    paymentStatus: "",
    orderStatus: "",
    cash_or_credit: "",
  });

  const url = buildQueryString("revenue/list", {
    page: query.page,
    limit: query.limit,
    search: queryStringOptions,
  });

  const {
    data: allRevenue,
    isSuccess: success,
    refetch,
  } = useGetApiQuery({ url });

  const [deleteRevenue] = useDeleteApiMutation();

  const pagination: PaginationType = {
    page: allRevenue?.data?.page ?? 1,
    limit: allRevenue?.data?.limit ?? 10,
    total: allRevenue?.data?.total ?? 0,
    totalPages: allRevenue?.data?.totalPages ?? 0,
  };

  const headers = [
    "S.N",
    "Date in AD",
    "Date in BS",
    "Member/Guest",
    "Payment Method",
    "Amount",
    "Remarks",
    "Cash/Credit",
    "Generated By",
    "Actions",
  ];

  const handleNewUser = (id: number | null) => {
    if (id === null) {
      navigate(REVENUE_ADD_ROUTE);
    } else {
      navigate(`${REVENUE_ADD_ROUTE}${id}`);
    }
  };

  const handleDeleteTrigger = (id: number) => {
    setDeleteId(id);
    setOpen(true);
  };

  const handleDelete = async () => {
    try {
      const response = await deleteRevenue(
        `${REVENUE_URL}${deleteId}`,
      ).unwrap();
      handleResponse({
        res: response,
        onSuccess: () => {
          refetch();
        },
      });
    } catch (error) {
      handleError({ error });
    } finally {
      setOpen(false);
    }
  };

  const data =
    success && allRevenue?.data?.data
      ? allRevenue?.data?.data.map(
          (
            {
              id,
              createdAt,
              cash_or_credit,
              paymentMethod,
              amount,
              remarks,
              user,
              customer,
            }: any,
            index: number,
          ) => {
            const adDate = createdAt ? new Date(createdAt) : null;
            const adDisplay = adDate ? format(adDate, "yyyy-MM-dd") : "";
            const bsDisplay = adDate ? ADToBS(adDate) : "";

            return [
              index + 1 + (pagination.page - 1) * pagination.limit,
              adDisplay,
              bsDisplay,
              customer ? customer.firstName : "Guest",
              paymentMethod,
              CurrencySign + amount,
              remarks ?? "",
              cash_or_credit,
              user?.username ?? "",
              <div className="flex items-center justify-center gap-3">
                <MdEditSquare
                  size={18}
                  className="text-[#0090DD] hover:text-blue-800"
                  onClick={() => handleNewUser(id)}
                />

                <DeleteModal
                  open={open}
                  setOpen={setOpen}
                  handleDeleteTrigger={() => handleDeleteTrigger(id)}
                  handleConfirmDelete={handleDelete}
                />
              </div>,
            ];
          },
        )
      : [];

  return (
    <>
      <PageTitle title="Revenue" />
      <PageHeader
        hasAddButton={true}
        newButtonText="Add Revenue"
        handleNewButton={() => handleNewUser(null)}
        handleReloadButton={() => refetch()}
      />

      <RevenueFilter
        queryStringOptions={queryStringOptions}
        setQueryStringOptions={setQueryStringOptions}
      />
      <Table
        headers={headers}
        data={data}
        pagination={pagination}
        handlePagination={handlePagination}
      />
      <div className="flex justify-end mt-4 ">
        <h1 className="text-2xl font-semibold border-b-[2px] border-[#E5E7EB] pb-2">
          Grand Total:
          <span className="text-green-600">
            {CurrencySign}
            {allRevenue?.data?.grandTotal ?? "###"}
          </span>
        </h1>
      </div>
    </>
  );
};

export default Revenue;
