import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import Table from "@/components/Table";
import TableRowActions from "@/components/Table/TableRowActions";
import MenuPageToolbar from "@/components/MenuPageToolbar";
import usePagination from "@/hooks/usePagination";
import { PaginationType } from "@/types/commonTypes";
import { CurrencySign } from "@/constants";
import RevenueFilter from "./RevenueFilter";
import { useDeleteApiMutation, useGetApiQuery } from "@/redux/services/crudApi";
import { buildQueryString } from "@/utils/generalHelper";
import { format } from "date-fns";
import { ADToBS } from "bikram-sambat-js";
import { REVENUE_ADD_ROUTE } from "@/routes/routeNames";
import { MdEditSquare } from "react-icons/md";
import DeleteModal from "@/components/DeleteModal";
import { handleError, handleResponse } from "@/utils/responseHandler";
import { REVENUE_URL } from "@/constants/apiUrlConstants";

const Revenue: React.FC = () => {
  const navigate = useNavigate();
  const { query, handlePagination } = usePagination({ page: 1, limit: 10 });

  const [open, setOpen] = useState<boolean>(false);
  const [deleteId, setDeleteId] = useState<number | null>(null);

  const [queryStringOptions, setQueryStringOptions] = useState({
    start: "",
    end: "",
    paymentStatus: "",
    orderStatus: "",
    cash_or_credit: "",
  });

  const url = buildQueryString("revenue/list", {
    page: query.page,
    limit: query.limit,
    search: queryStringOptions,
  });

  const {
    data: allRevenue,
    isSuccess: success,
    refetch,
  } = useGetApiQuery({ url });

  const [deleteRevenue] = useDeleteApiMutation();

  const pagination: PaginationType = {
    page: allRevenue?.data?.total === 0 ? 0 : allRevenue?.data?.page,
    limit: allRevenue?.data?.limit,
    total: allRevenue?.data?.total,
    totalPages: allRevenue?.data?.totalPages,
  };

  const headers = [
    "S.N",
    "Date (AD)",
    "Date (BS)",
    "Member/Guest",
    "Payment Method",
    "Amount",
    "Remarks",
    "Cash/Credit",
    "Generated By",
    "Actions",
  ];

  const handleNewUser = (id: number | null) => {
    if (id === null) {
      navigate(REVENUE_ADD_ROUTE);
    } else {
      navigate(`${REVENUE_ADD_ROUTE}${id}`);
    }
  };

  const handleDeleteTrigger = (id: number) => {
    setDeleteId(id);
    setOpen(true);
  };

  const handleDelete = async () => {
    try {
      const response = await deleteRevenue(
        `${REVENUE_URL}${deleteId}`,
      ).unwrap();
      handleResponse({
        res: response,
        onSuccess: () => {
          refetch();
        },
      });
    } catch (error) {
      handleError({ error });
    } finally {
      setOpen(false);
    }
  };

  const data =
    success && allRevenue?.data?.data
      ? allRevenue?.data?.data.map(
          (
            {
              id,
              createdAt,
              cash_or_credit,
              paymentMethod,
              amount,
              remarks,
              user,
              customer,
            }: any,
            index: number,
          ) => {
            const adDate = createdAt ? new Date(createdAt) : null;
            const adDisplay = adDate ? format(adDate, "yyyy-MM-dd") : "";
            const bsDisplay = adDate ? ADToBS(adDate) : "";

            return [
              index + 1 + (pagination.page - 1) * pagination.limit,
              adDisplay,
              bsDisplay,
              customer ? customer.firstName : "Guest",
              paymentMethod,
              <span className="font-semibold text-slate-800">
                {CurrencySign}
                {amount}
              </span>,
              <span
                className="mx-auto block max-w-full truncate"
                title={remarks ?? ""}
              >
                {remarks ?? ""}
              </span>,
              cash_or_credit,
              user?.username ?? "",
              <TableRowActions>
                <button
                  type="button"
                  onClick={() => handleNewUser(id)}
                  className="inline-flex h-8 w-8 items-center justify-center rounded-lg border border-sky-200 bg-sky-50 text-sky-600 transition hover:bg-sky-100"
                  title="Edit revenue"
                >
                  <MdEditSquare size={16} />
                </button>
                <DeleteModal
                  compact
                  open={open}
                  setOpen={setOpen}
                  handleDeleteTrigger={() => handleDeleteTrigger(id)}
                  handleConfirmDelete={handleDelete}
                />
              </TableRowActions>,
            ];
          },
        )
      : [];

  return (
    <div className="min-w-0 max-w-full overflow-x-hidden">
      <MenuPageToolbar
        showSearch={false}
        hasAddButton
        newButtonText="Add Revenue"
        handleNewButton={() => handleNewUser(null)}
        handleReloadButton={() => refetch()}
        subText="Track income, payment methods, and cash vs credit entries."
      />

      <RevenueFilter
        queryStringOptions={queryStringOptions}
        setQueryStringOptions={setQueryStringOptions}
      />

      <Table
        headers={headers}
        data={data}
        pagination={pagination}
        handlePagination={handlePagination}
      />

      <div className="mt-4 flex justify-end">
        <div className="rounded-xl border border-slate-200 bg-white px-4 py-3 shadow-sm">
          <span className="text-[13px] font-medium text-slate-600">
            Grand Total:{" "}
          </span>
          <span className="text-lg font-semibold text-emerald-600">
            {CurrencySign}
            {allRevenue?.data?.grandTotal ?? "0"}
          </span>
        </div>
      </div>
    </div>
  );
};

export default Revenue;
