import React, { useState } from "react";
import PageTitle from "@/components/PageTitle";
import Table from "@/components/Table";
import usePagination from "@/hooks/usePagination";
import { PaginationType } from "@/types/commonTypes";
import { CurrencySign } from "@/constants";
import RevenueFilter from "./RevenueFilter";
import { useGetApiQuery } from "@/redux/services/crudApi";
import { buildQueryString } from "@/utils/generalHelper";
import { format } from "date-fns";

const Revenue: React.FC = () => {
  const { query, handlePagination } = usePagination({ page: 1, limit: 10 });

  const [queryStringOptions, setQueryStringOptions] = useState({
    start: "",
    end: "",
    paymentStatus: "",
    orderStatus: "",
    cash_or_credit: "",
  });

  const url = buildQueryString("revenue/list", {
    page: query.page,
    limit: query.limit,
    search: queryStringOptions,
  });

  const { data: allRevenue, isSuccess: success } = useGetApiQuery({ url });

  const pagination: PaginationType = {
    page: allRevenue?.data?.page ?? 1,
    limit: allRevenue?.data?.limit ?? 10,
    total: allRevenue?.data?.total ?? 0,
    totalPages: allRevenue?.data?.totalPages ?? 0,
  };

  const headers = [
    "S.N",
    "Date",
    "Member/Guest",
    "Payment Method",
    "Amount",
    "Remarks",
    "Cash/Credit",
    "Generated By",
  ];

  const data =
    success && allRevenue?.data?.data
      ? allRevenue?.data?.data.map(
          (
            {
              createdAt,
              cash_or_credit,
              paymentMethod,
              amount,
              remarks,
              user,
              customer,
            }: any,
            index: number,
          ) => [
            index + 1 + (pagination.page - 1) * pagination.limit,
            createdAt ? format(new Date(createdAt), "PP p") : "",
            customer ? "Member" : "Guest",
            paymentMethod,
            CurrencySign + amount,
            remarks ?? "",
            cash_or_credit,
            user?.username ?? "",
          ],
        )
      : [];

  return (
    <>
      <PageTitle title="Revenue" />
      <RevenueFilter
        queryStringOptions={queryStringOptions}
        setQueryStringOptions={setQueryStringOptions}
      />
      <Table
        headers={headers}
        data={data}
        pagination={pagination}
        handlePagination={handlePagination}
      />
    </>
  );
};

export default Revenue;
