export const dummyOrders = [
  {
    id: "1",
    orderNumber: "ORD-001",
    orderType: "dineIn",
    tableId: "2",
    tableName: "Corner Booth",
    customerName: "John Smith",
    customerPhone: "+1234567890",
    customerEmail: "john.smith@email.com",
    orderItems: [
      {
        id: "item_1",
        productId: "1",
        productName: "Classic Margherita Pizza",
        productPrice: 18.99,
        quantity: 2,
        subtotal: 37.98,
        specialInstructions: "Extra cheese please",
      },
      {
        id: "item_2",
        productId: "6",
        productName: "Craft Beer",
        productPrice: 6.5,
        quantity: 2,
        subtotal: 13.0,
        specialInstructions: "",
      },
    ],
    totalAmount: 50.98,
    status: "preparing",
    orderNote: "Birthday celebration",
    estimatedTime: 20,
    createdAt: "2025-08-21T10:30:00Z",
    updatedAt: "2025-08-21T10:30:00Z",
  },
  {
    id: "2",
    orderNumber: "ORD-002",
    orderType: "takeaway",
    tableId: null,
    tableName: null,
    customerName: "Sarah Johnson",
    customerPhone: "+1987654321",
    customerEmail: "sarah.j@email.com",
    orderItems: [
      {
        id: "item_3",
        productId: "3",
        productName: "Caesar Salad",
        productPrice: 12.75,
        quantity: 1,
        subtotal: 12.75,
        specialInstructions: "Dressing on the side",
      },
      {
        id: "item_4",
        productId: "12",
        productName: "Fresh Orange Juice",
        productPrice: 4.99,
        quantity: 1,
        subtotal: 4.99,
        specialInstructions: "",
      },
    ],
    totalAmount: 17.74,
    status: "ready",
    orderNote: "",
    estimatedTime: 10,
    createdAt: "2025-08-21T11:15:00Z",
    updatedAt: "2025-08-21T11:25:00Z",
  },
  {
    id: "3",
    orderNumber: "ORD-003",
    orderType: "delivery",
    tableId: null,
    tableName: null,
    customerName: "Mike Davis",
    customerPhone: "+1555123456",
    customerEmail: "mike.davis@email.com",
    deliveryAddress: "123 Main Street, Apt 4B, New York, NY 10001",
    orderItems: [
      {
        id: "item_5",
        productId: "2",
        productName: "Grilled Chicken Breast",
        productPrice: 24.5,
        quantity: 1,
        subtotal: 24.5,
        specialInstructions: "Medium well done",
      },
      {
        id: "item_6",
        productId: "5",
        productName: "Fresh Salmon Fillet",
        productPrice: 28.75,
        quantity: 1,
        subtotal: 28.75,
        specialInstructions: "No asparagus",
      },
    ],
    totalAmount: 53.25,
    status: "completed",
    orderNote: "Leave at front door",
    estimatedTime: 35,
    createdAt: "2025-08-21T09:45:00Z",
    updatedAt: "2025-08-21T10:20:00Z",
  },
];
