export const dummyProducts = [
  {
    id: "1",
    name: "Classic Margherita Pizza",
    description:
      "Fresh tomato sauce, mozzarella cheese, basil leaves, olive oil",
    price: 18.99,
    quantity: 25,
    category: "Pizza",
    image: "/images/margherita-pizza.jpg",
    isActive: true,
    departmentId: 1,
    preparationTime: 15,
  },
  {
    id: "2",
    name: "Grilled Chicken Breast",
    description:
      "Herb-marinated chicken breast with seasonal vegetables and mashed potatoes",
    price: 24.5,
    quantity: 18,
    category: "Main Course",
    image: "/images/grilled-chicken.jpg",
    isActive: true,
    departmentId: 1,
    preparationTime: 20,
  },
  {
    id: "3",
    name: "Caesar Salad",
    description:
      "Crisp romaine lettuce, parmesan cheese, croutons, caesar dressing",
    price: 12.75,
    quantity: 30,
    category: "Salad",
    image: "/images/caesar-salad.jpg",
    isActive: true,
    departmentId: 2,
    preparationTime: 8,
  },
  {
    id: "4",
    name: "Chocolate Lava Cake",
    description:
      "Warm chocolate cake with molten center, served with vanilla ice cream",
    price: 9.99,
    quantity: 15,
    category: "Dessert",
    image: "/images/chocolate-lava-cake.jpg",
    isActive: true,
    departmentId: 3,
    preparationTime: 12,
  },
  {
    id: "5",
    name: "Fresh Salmon Fillet",
    description:
      "Pan-seared Atlantic salmon with lemon butter sauce and asparagus",
    price: 28.75,
    quantity: 12,
    category: "Seafood",
    image: "/images/salmon-fillet.jpg",
    isActive: true,
    departmentId: 1,
    preparationTime: 18,
  },
  {
    id: "6",
    name: "Craft Beer",
    description: "Local brewery IPA with citrus notes and hoppy finish",
    price: 6.5,
    quantity: 45,
    category: "Beverages",
    image: "/images/craft-beer.jpg",
    isActive: true,
    departmentId: 4,
    preparationTime: 2,
  },
  {
    id: "7",
    name: "Pasta Carbonara",
    description:
      "Traditional Italian pasta with pancetta, eggs, parmesan cheese",
    price: 19.25,
    quantity: 22,
    category: "Pasta",
    image: "/images/pasta-carbonara.jpg",
    isActive: true,
    departmentId: 1,
    preparationTime: 14,
  },
  {
    id: "8",
    name: "Veggie Burger",
    description:
      "Plant-based patty with avocado, lettuce, tomato, and sweet potato fries",
    price: 16.99,
    quantity: 20,
    category: "Vegetarian",
    image: "/images/veggie-burger.jpg",
    isActive: true,
    departmentId: 1,
    preparationTime: 12,
  },
  {
    id: "9",
    name: "Thai Tom Yum Soup",
    description:
      "Spicy and sour soup with shrimp, mushrooms, lemongrass, and lime leaves",
    price: 14.5,
    quantity: 16,
    category: "Soup",
    image: "/images/tom-yum-soup.jpg",
    isActive: true,
    departmentId: 1,
    preparationTime: 10,
  },
  {
    id: "10",
    name: "Tiramisu",
    description:
      "Classic Italian dessert with coffee-soaked ladyfingers and mascarpone",
    price: 8.75,
    quantity: 18,
    category: "Dessert",
    image: "/images/tiramisu.jpg",
    isActive: true,
    departmentId: 3,
    preparationTime: 5,
  },
  {
    id: "11",
    name: "BBQ Ribs",
    description: "Slow-cooked pork ribs with homemade BBQ sauce and coleslaw",
    price: 26.99,
    quantity: 14,
    category: "BBQ",
    image: "/images/bbq-ribs.jpg",
    isActive: true,
    departmentId: 1,
    preparationTime: 25,
  },
  {
    id: "12",
    name: "Fresh Orange Juice",
    description: "Freshly squeezed orange juice, no added sugar",
    price: 4.99,
    quantity: 35,
    category: "Beverages",
    image: "/images/orange-juice.jpg",
    isActive: true,
    departmentId: 4,
    preparationTime: 3,
  },
  {
    id: "13",
    name: "Mushroom Risotto",
    description: "Creamy arborio rice with mixed mushrooms and truffle oil",
    price: 21.5,
    quantity: 16,
    category: "Vegetarian",
    image: "/images/mushroom-risotto.jpg",
    isActive: true,
    departmentId: 1,
    preparationTime: 18,
  },
  {
    id: "14",
    name: "Chicken Wings",
    description:
      "Buffalo-style chicken wings with blue cheese dip and celery sticks",
    price: 13.99,
    quantity: 28,
    category: "Appetizer",
    image: "/images/chicken-wings.jpg",
    isActive: true,
    departmentId: 1,
    preparationTime: 12,
  },
  {
    id: "15",
    name: "Espresso",
    description: "Rich and aromatic double shot espresso",
    price: 3.5,
    quantity: 50,
    category: "Coffee",
    image: "/images/espresso.jpg",
    isActive: true,
    departmentId: 4,
    preparationTime: 2,
  },
];
