export const dummyTables = [
  {
    id: 1,
    floor: { id: 1, floorNo: "Main" },
    tableNo: "T1",
    name: "Window Side",
    type: "regular",
    capacity: 4,
    status: "available",
    currentSessionId: null,
    sessionStartTime: null,
    isActive: true,
  },
  {
    id: 2,
    floor: { id: 1, floorNo: "Main" },
    tableNo: "T2",
    name: "Corner Booth",
    type: "regular",
    capacity: 6,
    status: "occupied",
    currentSessionId: "550e8400-e29b-41d4-a716-446655440000",
    sessionStartTime: "2025-08-20T12:30:00Z",
    isActive: true,
  },
  {
    id: 3,
    floor: { id: 1, floorNo: "Main" },
    tableNo: "T3",
    name: null,
    type: "indoor",
    capacity: 2,
    status: "reserved",
    currentSessionId: "550e8400-e29b-41d4-a716-446655440001",
    sessionStartTime: "2025-08-20T14:00:00Z",
    isActive: true,
  },
  {
    id: 4,
    floor: { id: 2, floorNo: "Patio" },
    tableNo: "T4",
    name: "Patio Table",
    type: "outdoor",
    capacity: 4,
    status: "available",
    currentSessionId: null,
    sessionStartTime: null,
    isActive: true,
  },
  {
    id: 5,
    floor: { id: 3, floorNo: "Garden" },
    tableNo: "T5",
    name: "Garden View",
    type: "outdoor",
    capacity: 8,
    status: "occupied",
    currentSessionId: "550e8400-e29b-41d4-a716-446655440002",
    sessionStartTime: "2025-08-20T11:45:00Z",
    isActive: true,
  },
  {
    id: 6,
    floor: { id: 2, floorNo: "Patio" },
    tableNo: "T6",
    name: "VIP Lounge",
    type: "vip",
    capacity: 4,
    status: "reserved",
    currentSessionId: "550e8400-e29b-41d4-a716-446655440003",
    sessionStartTime: "2025-08-20T15:00:00Z",
    isActive: true,
  },
  {
    id: 7,
    floor: { id: 4, floorNo: "Rooftop" },
    tableNo: "T7",
    name: "Rooftop",
    type: "outdoor",
    capacity: 6,
    status: "maintenance",
    currentSessionId: null,
    sessionStartTime: null,
    isActive: false,
  },
  {
    id: 8,
    floor: { id: 4, floorNo: "Rooftop" },
    tableNo: "T8",
    name: null,
    type: "regular",
    capacity: 4,
    status: "available",
    currentSessionId: null,
    sessionStartTime: null,
    isActive: true,
  },
  {
    id: 9,
    floor: { id: 1, floorNo: "Main" },
    tableNo: "T9",
    name: "Family Table",
    type: "regular",
    capacity: 10,
    status: "occupied",
    currentSessionId: "550e8400-e29b-41d4-a716-446655440004",
    sessionStartTime: "2025-08-20T13:15:00Z",
    isActive: true,
  },
  {
    id: 10,
    floor: { id: 3, floorNo: "Garden" },
    tableNo: "T10",
    name: "Terrace",
    type: "outdoor",
    capacity: 2,
    status: "available",
    currentSessionId: null,
    sessionStartTime: null,
    isActive: true,
  },
  {
    id: 11,
    floor: { id: 4, floorNo: "Rooftop" },
    tableNo: "T11",
    name: "Private Room",
    type: "vip",
    capacity: 8,
    status: "reserved",
    currentSessionId: "550e8400-e29b-41d4-a716-446655440005",
    sessionStartTime: "2025-08-20T16:30:00Z",
    isActive: true,
  },
  {
    id: 12,
    floor: { id: 1, floorNo: "Main" },
    tableNo: "T12",
    name: null,
    type: "indoor",
    capacity: 4,
    status: "available",
    currentSessionId: null,
    sessionStartTime: null,
    isActive: true,
  },
];
